openapi: 3.0.0
info:
  title: API AEMPA - Sistema Administrativo
  version: 1.0.0
paths:
  /associados:
    post:
      summary: Cadastrar novo associado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
                telefone:
                  type: string
              required: [nome, email]
      responses:
        '201':
          description: Associado cadastrado com sucesso
        '400':
          description: Dados inválidos

  /movimentacoes:
    post:
      summary: Registrar entrada ou saída de valor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                associado_id:
                  type: integer
                tipo:
                  type: string
                  enum: [entrada, saida]
                valor:
                  type: number
              required: [associado_id, tipo, valor]
      responses:
        '201':
          description: Registro de movimentação criado com sucesso
        '400':
          description: Erro nos dados enviados

  /associados:
    get:
      summary: Listar todos os associados
      responses:
        '200':
          description: Lista de associados retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    email:
                      type: string
        '500':
          description: Erro interno no servidor